/// Group 31 - Formative Assignment 1
/// Firebase Configuration Options
///
/// This file is generated by FlutterFire CLI and contains platform-specific
/// Firebase configuration for Android and iOS.
///
/// IMPORTANT: This is a placeholder file. You must run 'flutterfire configure'
/// to generate the actual configuration with your Firebase project credentials.
///
/// To configure:
/// 1. Create a Firebase project at https://console.firebase.google.com/
/// 2. Run: flutterfire configure
/// 3. Select your Firebase project
/// 4. This file will be automatically updated with your project's credentials

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class provides platform-specific Firebase configuration options.
/// The [currentPlatform] getter automatically returns the correct configuration
/// based on the platform the app is running on (Android or iOS).
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the Firebase options for the current platform
  ///
  /// Automatically detects whether the app is running on Android or iOS
  /// and returns the appropriate configuration.
  ///
  /// Throws [UnsupportedError] if the platform is not supported
  /// (web, macOS, Windows, Linux).
  static FirebaseOptions get currentPlatform {
    // Web platform is not supported for this mobile-only app
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    // Return platform-specific configuration
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Android
  ///
  /// These values will be replaced when you run 'flutterfire configure'.
  /// The configuration includes:
  /// - apiKey: Your Firebase API key
  /// - appId: Your Firebase app ID
  /// - messagingSenderId: For Firebase Cloud Messaging
  /// - projectId: Your Firebase project ID
  /// - storageBucket: Your Firebase Storage bucket
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  /// Firebase configuration for iOS
  ///
  /// These values will be replaced when you run 'flutterfire configure'.
  /// iOS configuration includes an additional iosBundleId field.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.group31.formativeAssignment1',
  );
}
