/// Group 31 - Formative Assignment 1
/// Firebase Configuration Options
///
/// This file is generated by FlutterFire CLI and contains platform-specific
/// Firebase configuration for Android and iOS.
///
/// IMPORTANT: This is a placeholder file. You must run 'flutterfire configure'
/// to generate the actual configuration with your Firebase project credentials.
///
/// To configure:
/// 1. Create a Firebase project at https://console.firebase.google.com/
/// 2. Run: flutterfire configure
/// 3. Select your Firebase project
/// 4. This file will be automatically updated with your project's credentials

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This class provides platform-specific Firebase configuration options.
/// The [currentPlatform] getter automatically returns the correct configuration
/// based on the platform the app is running on (Android or iOS).
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the Firebase options for the current platform
  ///
  /// Automatically detects whether the app is running on Android or iOS
  /// and returns the appropriate configuration.
  ///
  /// Throws [UnsupportedError] if the platform is not supported
  /// (web, macOS, Windows, Linux).
  static FirebaseOptions get currentPlatform {
    // Web platform is not supported for this mobile-only app
    if (kIsWeb) {
      return web;
    }

    // Return platform-specific configuration
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Android
  ///
  /// These values will be replaced when you run 'flutterfire configure'.
  /// The configuration includes:
  /// - apiKey: Your Firebase API key
  /// - appId: Your Firebase app ID
  /// - messagingSenderId: For Firebase Cloud Messaging
  /// - projectId: Your Firebase project ID

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0qx0OVKKin25IrJUVphN3YDVU_VA2P9s',
    appId: '1:593104511265:android:2f9249398fdc612a44de60',
    messagingSenderId: '593104511265',
    projectId: 'group31-formative-assignment1',
    storageBucket: 'group31-formative-assignment1.firebasestorage.app',
  );

  /// - storageBucket: Your Firebase Storage bucket

  /// Firebase configuration for iOS
  ///
  /// These values will be replaced when you run 'flutterfire configure'.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLxKR-_vH443y1lSpzN64lYgqVUyCpTTQ',
    appId: '1:593104511265:ios:ec5b93e61d42361944de60',
    messagingSenderId: '593104511265',
    projectId: 'group31-formative-assignment1',
    storageBucket: 'group31-formative-assignment1.firebasestorage.app',
    iosBundleId: 'com.example.aluAcademicPlatform',
  );

  /// iOS configuration includes an additional iosBundleId field.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FEb3SEt-JdtwcEXSMDRMkDI2HG84DCw',
    appId: '1:593104511265:web:4a5f0d18921f552244de60',
    messagingSenderId: '593104511265',
    projectId: 'group31-formative-assignment1',
    authDomain: 'group31-formative-assignment1.firebaseapp.com',
    storageBucket: 'group31-formative-assignment1.firebasestorage.app',
  );

}